version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - err113
    - intrange
    - nlreturn
    - paralleltest
    - revive
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 50
    funlen:
      lines: 150
      statements: 150
    lll:
      line-length: 160
    depguard:
      rules:
        test:
          files:
            - "$test"
          allow:
            - "$gostd"
            - github.com/michurin/systemd-env-file/sdenv
            - github.com/stretchr/testify/
  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - path: cmd/xenv/main.go
        linters:
          - gosec
      - path: cmd/xenv/main.go
        source: "\\sfmt\\.Fprint(ln|f)\\("
        linters:
          - errcheck
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/michurin/systemd-env-file)
