linters:
  enable-all: true
  disable:
      # deprecated
    - tenv
      # disabled because the Go version (1.20)
    - copyloopvar
    - intrange
      # project too small to be such paranoiac
    - depguard
    - err113
    - nlreturn
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/michurin/systemd-env-file)
  lll: {line-length: 160}
  funlen: {statements: 150, lines: 150} # parsers are long
  cyclop: {max-complexity: 50}          # and "complex"
