---
name: build # this string appears on badge
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.20"
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
    name: "Go ${{ matrix.go }} build and integration test"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go }}"
      - run: "cmd/xenv/ci/run"
  test:
    runs-on: ubuntu-latest
    name: "Unit test and lint"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - uses: golangci/golangci-lint-action@v7
        with:
          version: "v2.1.5"
      - run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./sdenv/..."
        env:
          GOEXPERIMENT: nocoverageredesign
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          files: ./coverage.txt
          verbose: true
